### ISSUE TITLE
VID react anchor missing

### ISSUE THREAD

**Issue by greggirwin** [red/docs#218]
From @endo64: https://github.com/red/docs/blob/master/en/vid.adoc#3-container-settings has a link that goes nowhere.

**Comment by endo64** [comment]
It looks it is fixed.

**Comment by greggirwin** [comment]
Hmmm. Still goes nowhere for me.

**Comment by endo64** [comment]
Link is https://github.com/red/docs/blob/master/en/vid.adoc#actors 

![image](https://user-images.githubusercontent.com/840604/75379559-a4461480-58e6-11ea-8607-82986c5d379c.png)

It works for me now, any caching issue?

**Comment by greggirwin** [comment]
Tried a hard refresh, but still get https://doc.red-lang.org/en/vid.html#anchor:_react as the link. Ah, the web.
